Repository Dev-FE-1/ToyProject_3_Team2, pull requests merged in 2024-09, with the labels that each got.

#82 [Refactor] Dialog 재생목록 URL로 유튜브 API 호출
  src/api/youtube.ts
  src/components/YouTubePlayerV3.tsx
  src/components/common/modals/Dialog.tsx
  src/hooks/useVideoData.ts
  src/pages/Home.tsx
Labels: Refactor

#87 [Database] 파이어스토어 데이터 구조 수정
  src/api/index.ts
  src/mock/data.ts
Labels: API

#84 [Refactor] MyPlaylist (플립오버 카드) 기능개선
  src/components/mypage/MyPlaylists.tsx
Labels: Refactor

#91 [feat] thumbox 컴포넌트 수정
  src/components/common/ThumBox.tsx
  src/styles/theme.ts
Labels: Html&css

#88 [ Feat] 검색 페이지 > 카테고리 필터링
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/api/endpoints/comment.ts
  src/api/endpoints/playlist.ts
  src/api/endpoints/resetAndSetupData.ts
  src/api/endpoints/user.ts
  src/api/endpoints/youtube.ts
  src/api/index.ts
  src/components/YouTubePlayerV3.tsx
  src/components/common/ThumBox.tsx
  src/components/common/buttons/CommentsButton.tsx
  src/components/common/buttons/LikesButton.tsx
  src/components/common/modals/Dialog.tsx
  src/components/search/CategoryButtons.tsx
  src/components/search/FilteredPlaylists.tsx
  src/constants/playlist.ts
  src/constants/queryKey.ts
  src/hooks/query/usePlaylist.ts
  src/hooks/query/useYoutube.ts
  src/hooks/usePlaylistByCategory.ts
  src/mock/data.ts
  src/mock/dataStructure.json
  src/mock/playlists.json
  src/pages/Search.tsx
  src/pages/Test/FirebaseTest.tsx
  src/styles/GlobalStyle.tsx
  src/types/playlist.d.ts
  src/utils/formatDate.ts
  src/utils/formatNumber.ts
Labels: Feature

#90 [Feat] 새 재생목록 만들기 기능 및 저장
  src/App.tsx
  src/api/endpoints/playlist.ts
  src/api/index.ts
  src/components/common/SelectBox.tsx
  src/components/common/Toast.tsx
  src/components/common/ToggleSwitch.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/modals/Dialog.tsx
  src/components/mypage/FlipCard.tsx
  src/components/mypage/MyPlaylists.tsx
  src/components/mypage/MyProfile.tsx
  src/components/playlist/StarToggleButton.tsx
  src/components/playlistForm/PlaylistForm.tsx
  src/components/search/FilteredPlaylists.tsx
  src/components/subscriptions/SubsToggleButton.tsx
  src/constants/path.ts
  src/constants/playlist.ts
  src/hooks/useLikeCount.ts
  src/hooks/usePlaylistForm.ts
  src/layouts/layout/Navbar.tsx
  src/mock/data.ts
  src/pages/Mypage.tsx
  src/pages/PlaylistAdd.tsx
  src/pages/Settings.tsx
  src/store/useLikeStore.ts
  src/store/useModalStore.ts
  src/store/usePlaylistStore.ts
  src/store/useToastStore.ts
  src/store/useToggleStore.ts
  src/types/playlist.d.ts
  src/utils/string.ts
Labels: Feature, Html&css, API

#92 [Feat] 플레이리스트 메인 페이지 퍼블리싱
  src/App.tsx
  src/components/common/VideoCard.tsx
  src/components/playlistdetail/thumBoxDetail.tsx
  src/components/playlistdetail/vedieoBoxDetail.tsx
  src/components/profile/Profile.tsx
  src/pages/PlayList.tsx
Labels: Feature, Html&css

#93 [Feat] 홈 가로스크롤 구현
  src/api/index.ts
  src/components/common/ThumBox.tsx
  src/components/common/buttons/IconTextButton.tsx
  src/components/home/PlaylistSextion.tsx
  src/pages/Home.tsx
  src/pages/Signin.tsx
Labels: Feature, Html&css

#95 [Feat] 재생목록 페이지 구현 중간 PR
  src/components/playlist/PlaylistBox.tsx
  src/components/profile/Profile.tsx
  src/pages/Subscriptions.tsx
Labels: Feature, Html&css

#96 [Feat] login auth 연결
  src/App.tsx
  src/constants/path.ts
  src/layouts/RootLayout.tsx
  src/pages/Onboarding.tsx
  src/pages/Signin.tsx
  src/store/authStore.ts
Labels: Feature

#97 [Feat] 홈 전체보기로 넘어가는 상세페이지 퍼블리싱 완료
  src/App.tsx
  src/api/index.ts
  src/components/common/ThumBox.tsx
  src/components/home/PlaylistSextion.tsx
  src/components/home/SectionListPage.tsx
  src/pages/Home.tsx
  src/pages/Signin.tsx
Labels: Feature, Html&css

#100 [Feat] 데이터베이스 Users 컬렉션 수정
  src/App.tsx
  src/api/endpoints/resetAndSetupData.ts
  src/mock/data.ts
Labels: API

#104 [Feat] 스피너 컴포넌트 생성
  src/components/common/Spinner.tsx
Labels: Feature, BugFix, Html&css

#107 [Feat] favicon 추가
  index.html
  src/assets/images/favicon/android-chrome-192x192.png
  src/assets/images/favicon/android-chrome-512x512.png
  src/assets/images/favicon/apple-touch-icon.png
  src/assets/images/favicon/favicon-16x16.png
  src/assets/images/favicon/favicon-32x32.png
  src/assets/images/favicon/favicon.ico
  src/assets/images/favicon/favicon.png
  src/assets/images/favicon/favicon.svg
  src/assets/images/favicon/safari-pinned-tab.svg
  src/assets/images/site.webmanifest
Labels: Feature, Html&css

#108 [Feat]/home 퍼블리싱 완료
  src/App.tsx
  src/components/home/PlaylistSextion.tsx
  src/components/home/RecentUpdateSection.tsx
  src/components/home/SectionListPage.tsx
  src/pages/Home.tsx
Labels: Feature, Html&css

#112 [Feat] 검색 페이지 키워드별 필터링 기능 구현
  src/api/endpoints/playlist.ts
  src/components/common/Spinner.tsx
  src/components/home/PlaylistSection.tsx
  src/components/home/RecentUpdateSection.tsx
  src/components/home/SectionListPage.tsx
  src/components/search/CategoryButtons.tsx
  src/components/search/FilteredPlaylists.tsx
  src/components/search/Input.tsx
  src/constants/playlist.ts
  src/hooks/query/usePlaylist.ts
  src/hooks/useFilteredPlaylists.ts
  src/hooks/usePlaylistByCategory.ts
  src/pages/Home.tsx
  src/pages/Search.tsx
  src/styles/GlobalStyle.tsx
  src/types/playlist.d.ts
Labels: Feature

#110 [Feat]마이페이지에 마이프로필 컴포넌트 와 파이어베이스 유저 연동
  index.html
  src/api/endpoints/playlist.ts
  src/api/endpoints/user.ts
  src/assets/images/manifest.json
  src/assets/images/site.webmanifest
  src/components/mypage/MyPlaylists.tsx
  src/components/mypage/MyProfile.tsx
  src/pages/Mypage.tsx
  src/types/user.ts
Labels: Feature, Html&css, API

#113 [fix] dialog 비활성화 수정
  src/components/common/modals/Dialog.tsx
Labels: BugFix

#118 [feat] 메인에서 플리 클릭시 상세페이지로 이동
  src/App.tsx
  src/components/home/PlaylistSection.tsx
  src/components/home/RecentUpdateSection.tsx
  src/components/home/SectionListPage.tsx
  src/pages/PlayList.tsx
Labels: Feature

#119 [Feat] 플레이리스트 페이지 구현, 새 플레이리스트 생성기능 수정, 디자인 및 마크업 수정
  src/App.tsx
  src/api/endpoints/playlist.ts
  src/api/endpoints/user.ts
  src/assets/images/default-thumb.svg
  src/components/common/VideoCard.tsx
  src/components/common/buttons/CommentsButton.tsx
  src/components/mypage/FlipCard.tsx
  src/components/mypage/MyProfile.tsx
  src/components/playlistdetail/thumBoxDetail.tsx
  src/components/playlistdetail/vedieoBoxDetail.tsx
  src/components/profile/Profile.tsx
  src/constants/path.ts
  src/layouts/layout/Header.tsx
  src/mock/data.ts
  src/pages/Home.tsx
  src/pages/Mypage.tsx
  src/pages/PlaylistAdd.tsx
  src/pages/PlaylistPage.tsx
  src/types/playlist.d.ts
  src/types/user.d.ts
Labels: Feature, Html&css, API

#123 [Fea t] 구글로 로그인 기능 구현 완료
  src/components/common/Input.tsx
  src/components/common/buttons/Button.tsx
  src/components/signin/GoogleLogin.tsx
  src/pages/Signin.tsx
Labels: Feature

#125 [Feat] 플레이리스트메인 퍼블리싱마무리 + 플레이리스트 삭제 api
  public/videonull.svg
  src/App.tsx
  src/api/endpoints/playlist.ts
  src/components/common/modals/BottomSheet.tsx
  src/components/playlistdetail/nullBox.tsx
  src/layouts/layout/Header.tsx
  src/pages/PlaylistPage.tsx
  src/pages/Settings.tsx
Labels: Feature

#131 [Feat] 댓글 목록 페이지 퍼블리싱 및 데이터베이스 연동
  src/App.tsx
  src/api/endpoints/comment.ts
  src/api/endpoints/playlist.ts
  src/components/comment/CommentBox.tsx
  src/components/common/buttons/CommentsButton.tsx
  src/constants/path.ts
  src/constants/queryKey.ts
  src/hooks/query/useComments.ts
  src/pages/CommentList.tsx
  src/types/playlist.d.ts
Labels: Feature, Html&css

#134 [Refactor] playwright로 온보딩페이지와 로그인페이지에서 로그인후 홈까지 오는 테스트 코드 작성
  package-lock.json
  package.json
  playwright.config.ts
  src/tests/SigninTest.test.ts
Labels: Refactor

#136 [Feat] 플레이리스트 메인페이지 수정,삭제,비디오삭제
  src/App.tsx
  src/api/endpoints/playlist.ts
  src/components/common/modals/BottomSheet.tsx
  src/components/playlistForm/PlaylistForm.tsx
  src/components/playlistdetail/thumBoxDetail.tsx
  src/constants/path.ts
  src/hooks/useAuthStaus.ts
  src/hooks/usePlaylistData.ts
  src/pages/PlaylistAdd.tsx
  src/pages/PlaylistEdit.tsx
  src/pages/PlaylistPage.tsx
Labels: Feature

#140 [Feat] 플레이리스트 메인 페이지에서 유튜브 API를 사용해 동영상 등록
  src/api/endpoints/playlist.ts
  src/api/endpoints/youtube.ts
  src/components/common/VideoCard.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/modals/Dialog.tsx
  src/components/mypage/MyProfile.tsx
  src/components/playlistdetail/VideoBoxDetail.tsx
  src/components/playlistdetail/thumBoxDetail.tsx
  src/hooks/useAddVideo.ts
  src/mock/data.ts
  src/pages/Mypage.tsx
  src/pages/PlaylistEdit.tsx
  src/pages/PlaylistPage.tsx
  src/pages/Settings.tsx
  src/types/playlist.d.ts
  src/utils/formatDate.ts
  src/utils/formatTime.ts
  src/utils/getVideoId.ts
  src/utils/user.ts
Labels: Feature, API

#139 [feat] 댓글 작성 페이지 퍼블리싱
  src/App.tsx
  src/constants/path.ts
  src/pages/CommentForm.tsx
  src/pages/CommentList.tsx
Labels: Html&css

#138 [Feat] 상세 비디오모달 컴포넌트 구현(전역 미니 플레이리스트 함께 구현)
  src/components/playlistdetail/VideoBoxDetail.tsx
  src/components/playlistdetail/thumBoxDetail.tsx
  src/components/profile/Profile.tsx
  src/components/videoModal/VideoModal.tsx
  src/layouts/RootLayout.tsx
  src/layouts/layout/Header.tsx
  src/pages/PlaylistPage.tsx
  src/pages/Settings.tsx
  src/store/useMiniPlayerStore.ts
Labels: Feature, BugFix, Html&css

#144 [feat] 플레이리스트 댓글 작성 기능
  src/App.tsx
  src/api/endpoints/comment.ts
  src/components/commentForm/CommentForm.tsx
  src/constants/path.ts
  src/pages/CommentAdd.tsx
  src/pages/CommentList.tsx
Labels: Feature

#145 [Feat] 내 댓글 삭제 기능 구현
  src/api/endpoints/comment.ts
  src/components/comment/CommentBox.tsx
  src/hooks/query/useComments.ts
  src/pages/CommentList.tsx
  src/types/playlist.d.ts
Labels: Feature, Html&css

#149 [Feat] 플레이리스트 상세페이지 Draggable 기능
  package-lock.json
  package.json
  src/api/endpoints/playlist.ts
  src/components/playlistdetail/VideoBoxDetail.tsx
  src/components/videoModal/VideoModal.tsx
  src/main.tsx
  src/pages/PlaylistPage.tsx
Labels: Feature, Html&css, API

#152 [Design] 댓글 css 일부 수정
  src/components/comment/CommentBox.tsx
Labels: Html&css

#150 [feat] 기존 댓글 카운트, 댓글 작성시 카운트 +1
  src/api/endpoints/comment.ts
  src/api/endpoints/playlist.ts
  src/pages/CommentList.tsx
Labels: Feature, API

#155 [fix] 모달 컴포넌트, 첫진입시 404 에러 해결
  src/api/endpoints/comment.ts
  src/api/endpoints/playlist.ts
  src/layouts/layout/Navbar.tsx
  src/pages/CommentList.tsx
  src/pages/PlaylistPage.tsx
Labels: BugFix

#162 [Feat] 유튜브 공유하기링크, 쇼츠 영상 링크 처리
  src/utils/getVideoId.ts
Labels: Feature, API

#164 [feat] 탐색페이지 카테고리 가로 스크롤 구현
  src/components/page/home/CrossScrollingList.tsx
  src/components/page/search/CategoryButtons.tsx
  src/hooks/useDragToScroll.ts
Labels: Feature

#169 [Fix] PlaylistPage와 VideoModal 컴포넌트의 버그 픽스
  src/components/page/playlistdetail/VideoBoxDetail.tsx
  src/components/page/videoModal/VideoModal.tsx
  src/pages/Mypage.tsx
  src/pages/PlaylistPage.tsx
Labels: BugFix

#170 [Feat] 플레이리스트 메인 mutation
  src/components/common/modals/BottomSheet.tsx
  src/constants/queryKey.ts
  src/hooks/mutations/usePlaylistMutations.ts
  src/hooks/queries/usePlaylistQueries.ts
  src/hooks/usePlaylistData.ts
  src/pages/PlaylistEdit.tsx
  src/pages/PlaylistPage.tsx
Labels: Feature, API

#159 [Feat] 구독 토글 버튼에 API 연결해 클릭마다 요청 보내는 기능 구현
  src/components/page/playlist/PlaylistBox.tsx
  src/components/page/profile/Profile.tsx
  src/components/page/subscriptions/SubsToggleButton.tsx
  src/pages/PlaylistPage.tsx
  src/pages/Subscriptions.tsx
Labels: Feature

#168 [Feat] 내 댓글 삭제하기 추가 작업
  src/api/endpoints/comment.ts
  src/components/page/comment/CommentBox.tsx
  src/pages/CommentList.tsx
  src/types/playlist.d.ts
Labels: Feature, API

#172 [Fix] 플레이리스트의 업로더를 클릭하면 해당 업로더의 마이페이지가 아닌 내 마이페이지로 이동하는 버그 수정
  src/hooks/queries/useUserQueries.ts
  src/pages/Mypage.tsx
Labels: Feature, BugFix

#167 [Feat] 홈페이지 최신 플리 무한스크롤, 업데이트 순서로 정렬
  src/api/endpoints/playlist.ts
  src/components/page/home/RecentUpdateList.tsx
  src/hooks/queries/usePlaylistQueries.ts
  src/hooks/useInfiniteScroll.ts
  src/utils/sortPlaylists.ts
Labels: Feature, API

#174 [Feat] 비디오모달에서 동영상 삭제 기능 추가 및 업데이트된 동영상 순서대로 인덱스 보여지는 기능 추가
  src/components/page/comment/CommentBox.tsx
  src/components/page/playlistdetail/VideoBoxDetail.tsx
  src/components/page/videoModal/VideoModal.tsx
  src/hooks/mutations/usePlaylistMutations.ts
  src/hooks/usePlaylistData.ts
  src/pages/PlaylistPage.tsx
Labels: Feature

#178 [Refactor] 이미지가 없을 경우 디폴트 이미지 추가, 비공개 플레이리스트 렌더링되는 오류 수정
  src/App.tsx
  src/api/endpoints/playlistFetch.ts
  src/api/endpoints/resetAndSetupData.ts
  src/assets/default-playlist-cover.webp
  src/components/YouTubePlayerV3.tsx
  src/components/commentForm/CommentForm.tsx
  src/components/common/PlaylistItem.tsx
  src/components/common/ToggleSwitch.tsx
  src/components/page/home/RecentUpdateList.tsx
  src/components/page/playlistAdd/PlaylistForm.tsx
  src/components/page/playlistdetail/thumBoxDetail.tsx
  src/components/page/search/FilteredPlaylists.tsx
  src/components/page/videoModal/VideoModal.tsx
  src/constants/ normal.ts
  src/hooks/usePlaylistForm.ts
  src/hooks/useSortedPlaylists.ts
  src/pages/CommentList.tsx
  src/pages/PlaylistPage.tsx
  src/router/Router.tsx
  src/store/useLikeStore.ts
  src/utils/formatDate.ts
Labels: BugFix

#190 [Fix] 댓글 필터링 오류 수정
  src/pages/CommentList.tsx
Labels: BugFix

#193 [Fix] 비디오 모달에서 비디오 영상 순서 변경 시 변경된 인덱스로 상위에 보여지도록 수정
  src/components/page/videoModal/VideoModal.tsx
Labels: BugFix

#195 [fix] 로그인여부에 따라 로그인페이지로 이동 및 404페이지 이동
  src/pages/Mypage.tsx
  src/pages/PlaylistEdit.tsx
  src/pages/PlaylistPage.tsx
  src/router/Router.tsx
Labels: BugFix

#197 [fix] 플레이리스트 수정시 기존 썸네일 이미지 안나오는 현상
  src/hooks/usePlaylistForm.ts
Labels: BugFix

#203 [feat] 구독 페이지 없을 때 표시
  src/constants/playlist.ts
  src/pages/Onboarding.tsx
  src/pages/Subscriptions.tsx
Labels: Html&css

#205 [docs] Update README (#189)
  README.md
Labels: Docs

#208 [Fix] 댓글 추가 시 플레이리스트 페이지에서 생기는 라우팅 버그 해결
  src/TestCommentPage.tsx
  src/components/common/Spinner.tsx
  src/components/page/home/CrossScrollingList.tsx
  src/components/page/home/DetailList.tsx
  src/components/page/home/RecentUpdateList.tsx
  src/components/page/mypage/FlipCard.tsx
  src/components/page/playlist/PlaylistBox.tsx
  src/components/page/search/FilteredPlaylists.tsx
  src/components/page/search/Input.tsx
  src/hooks/queries/useCommentsQueries.ts
  src/hooks/useFilteredPlaylists.ts
  src/mock/playlists.json
  src/pages/CommentList.tsx
  src/pages/PlaylistPage.tsx
  src/pages/Search.tsx
  src/store/usePrevUrlStore.ts
Labels: BugFix

#210 [Fix] 메인페이지 내 관심사와 비슷한 플레이리스트에서 나의 플레이리스트도 나오는 버그 수정
  src/hooks/useSortedPlaylists.ts
  src/utils/formatDate.ts
Labels: BugFix

#211 [feat] 로그인 후 플리 추가하는 테스트코드 작성
  src/tests/PlaylistCreate.test.ts
Labels: Feature

#214 [Docs] 리드미 수정
  README.md
Labels: Docs

#224 [Refactor] 댓글 필터링 기능 리팩토링 및 데이터 상수화 작업
  src/components/page/comment/CommentBox.tsx
  src/constants/comment.ts
  src/constants/title.ts
  src/pages/CommentList.tsx
  src/pages/Subscriptions.tsx
Labels: Refactor

#225 [Refactor] 구글 로그인시 userPlaylists 초기화 문제 해결
  src/components/page/signin/GoogleLogin.tsx
  src/pages/Signin.tsx
Labels: Refactor

#228 [refactor] section-list 경로 변수명으로 변경
  src/components/page/home/CrossScrollingList.tsx
  src/pages/PlaylistPage.tsx
  src/router/Router.tsx
Labels: Refactor

#230 [refactor] 로그인 테스트 코드 beforeEach로 반복 처리
  src/tests/SigninTest.test.ts
Labels: Refactor

#232 [Refactor] 무한스크롤 코드 내 시간딜레이, 컨텐츠 반복 삭제
  src/components/page/home/RecentUpdateList.tsx
Labels: Refactor

#236 [Refactor] input과 signin페이지 리펙토링
  src/components/common/Input.tsx
  src/pages/Signin.tsx
Labels: Refactor

#238 [refactor] 타입에러, lint에러, 사용되지않은 선언 제거
  .eslintrc.cjs
  src/components/common/modals/Dialog.tsx
  src/components/page/playlist/PlaylistBox.tsx
  src/components/page/search/CategoryButtons.tsx
  src/hooks/useDragToScroll.ts
Labels: Refactor

#240 [Fix] 스피너 위치 수정 및 관련 중복코드 삭제
  src/components/common/Spinner.tsx
  src/components/page/home/RecentUpdateList.tsx
  src/components/page/videoModal/VideoModal.tsx
  src/pages/Home.tsx
  src/pages/Mypage.tsx
  src/pages/PlaylistAdd.tsx
  src/pages/PlaylistPage.tsx
Labels: BugFix, Html&css

#244 [Feat] 댓글 프로필 클릭 시 개인 페이지로 라우팅 설정
  src/components/page/comment/CommentBox.tsx
Labels: Feature

#249 [Fix] 플레이리스트 메인 모달 오류
  src/pages/PlaylistPage.tsx
Labels: BugFix

#250 [refactor] 로그인 테스트코드 온보딩 처리 수정
  src/tests/SigninTest.test.ts
Labels: Refactor

#251 feat: 비디오 삭제 시 새로 인덱스 업데이트 기능 추가 (#242)
  src/components/page/videoModal/VideoModal.tsx
Labels: Feature

#252 [Fix] 안쓰는 변수 삭제 및 eslint 수정
  .eslintrc.cjs
  src/components/page/videoModal/VideoModal.tsx
Labels: BugFix

#254 [Refactor] CommentBox.tsx 코드 개선
  src/api/endpoints/playlistFetch.ts
  src/components/page/comment/CommentBox.tsx
  src/constants/comment.ts
  src/pages/CommentList.tsx
Labels: Refactor

#255 [feat] 가로스크롤 버튼 추가
  src/components/page/home/CrossScrollingList.tsx
  src/components/page/home/HorizontalList.tsx
  src/components/page/search/CategoryButtons.tsx
  src/hooks/useDragToScroll.ts
  src/hooks/useScrollWithArrows.ts
  src/pages/Home.tsx
Labels: Feature

#258 feat: 댓글 삭제 시 모달창 생성 및 필터링 버그 수정(#245)
  src/components/common/modals/Dialog.tsx
  src/components/page/comment/CommentBox.tsx
  src/pages/CommentList.tsx
Labels: Feature, BugFix, Refactor

#260 [fix] 메인페이지에서 출력되는 오류 해결
  src/components/page/home/HorizontalList.tsx
  src/hooks/useScrollWithArrows.ts
Labels: BugFix

#262 fix: 자세히보기 버튼 아이콘 위치 수정 (#261)
  src/components/common/buttons/IconTextButton.tsx
  src/components/page/home/HorizontalList.tsx
Labels: BugFix, Html&css

#263 [Fix] 크롬 첫 진입시 온보딩페이지보다 로그인페이지가 먼저 랜더링되는 버그
  src/router/Router.tsx
Labels: BugFix

#264 [Fix] settings
  package-lock.json
  package.json
Labels: Setting, BugFix

#267 [Fix] 좋아요 1000개 이상일 때 뱃지가 보이지 않는 문제 수정 (#241)
  src/components/page/mypage/MyProfile.tsx
Labels: BugFix
