Repository Dev-FE-1/ToyProject_3_Team2, pull requests merged in 2024-08, with the labels that each got.

#4 [Feat] 글로벌스타일, 폰트, 테마 생성 및 적용
  index.html
  src/assets/fonts/woff/Pretendard-Black.woff
  src/assets/fonts/woff/Pretendard-Bold.woff
  src/assets/fonts/woff/Pretendard-ExtraBold.woff
  src/assets/fonts/woff/Pretendard-ExtraLight.woff
  src/assets/fonts/woff/Pretendard-Light.woff
  src/assets/fonts/woff/Pretendard-Medium.woff
  src/assets/fonts/woff/Pretendard-Regular.woff
  src/assets/fonts/woff/Pretendard-SemiBold.woff
  src/assets/fonts/woff/Pretendard-Thin.woff
  src/main.tsx
  src/styles/ theme.ts
  src/styles/GlobalStyle.tsx
  src/styles/emotion.d.ts
  src/styles/fonts.d.ts
  src/styles/globalFonts.ts
  src/types/global.d.ts
Labels: Feature, Html&css

#10 [Feat] 라우터 생성, 각 페이지와 네비게이션을 라우터에 연결 (#6, #7)
  package-lock.json
  package.json
  src/App.tsx
  src/constants/path.ts
  src/layouts/RootLayout.tsx
  src/layouts/layout/Navbar.tsx
  src/pages/Home.tsx
  src/pages/Mypage.tsx
  src/pages/Search.tsx
  src/pages/Signin.tsx
  src/pages/Subscriptions.tsx
Labels: Feature

#9 상태 관리 의존성 설치
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/ExampleTanStackQuery.tsx
  src/store/store.ts
Labels: Setting, Feature

#15 [Fix] 크리티컬한 오타 수정 및 상태관리 예시페이지 분리, 파일명 수정 및 경로 수정
  package-lock.json
  package.json
  src/App.tsx
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/pages/ExamplePage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: BugFix

#16 [Feat] 네비게이션 컴포넌트 생성
  package-lock.json
  package.json
  src/constants/path.ts
  src/layouts/layout/Navbar.tsx
  tsconfig.node.json
Labels: Feature, Html&css

#17 [Feat] 버튼 컴포넌트 생성
  src/components/buttons/Button.tsx
Labels: Feature, Html&css

#19 [Feat] 아이콘 + 텍스트 버튼 컴포넌트 생성
  src/components/common/buttons/IconTextButton.tsx
Labels: Feature, Html&css

#20 [Feat] 원형 아이콘 버튼 생성
  package-lock.json
  src/components/common/buttons/Button.tsx
  src/components/common/buttons/IconButton.tsx
Labels: Feature, Html&css

#32 [Feat] 헤더 컴포넌트 생성
  src/layouts/layout/Header.tsx
Labels: Feature, Html&css

#33 [feat] SwitchToggle 컴포넌트 작성
  package-lock.json
  package.json
  src/components/buttons/SwitchToggle.tsx
Labels: Feature, Html&css

#38 [Feat] YoutubeAPI
  .gitignore
  package-lock.json
  package.json
  src/components/YouTubePlayerV3.tsx
  src/pages/ExamplePage.tsx
  src/vite-env.d.ts
Labels: Feature, API

#41 [Feat] badge 컴포넌트 생성
  src/components/ToggleSwitch.tsx
  src/components/common/Badge.tsx
Labels: Feature, Html&css

#42 [Fix] 비디오 카드에서도 확장성 있는 Badge 컴포넌트 수정
  src/components/common/Badge.tsx
  src/components/common/ToggleSwitch.tsx
Labels: Feature, BugFix

#39 [Feat] Profile 컴포넌트
  src/components/profile/Profile.tsx
  src/pages/ExamplePage.tsx
Labels: Html&css

#48 [Feat] 파이어베이스 초기 세팅
  package-lock.json
  package.json
  src/firebase/firebase.js
Labels: Setting, API

#46 [Feat] Thumbox 컴포넌트
  src/components/common/ThumBox.tsx
  src/pages/ExamplePage.tsx
Labels: Feature, Html&css

#47 [Feat] Axios 활용을 통한 TanStack Query 사용 추상화 (Youtube API)
  .env
  .gitignore
  src/api/youtubeApi.ts
  src/components/YouTubePlayerV3.tsx
  src/hooks/useVideoData.ts
  src/pages/ExamplePage.tsx
  src/utils/getVideoId.ts
Labels: Feature, API

#49 [Feat] modal center 컴포넌트 작성
  package-lock.json
  package.json
  src/components/common/modals/Dialog.tsx
Labels: Feature, Html&css

#51 [Fix] 네비게이션 배경 추가
  .gitignore
  src/layouts/layout/Navbar.tsx
Labels: BugFix

#52 [Feat] VideoCard 컴포넌트
  src/components/common/VideoCard.tsx
  src/pages/ExamplePage.tsx
Labels: Feature, Html&css

#56 [Feat] Toast 컴포넌트
  src/components/common/Toast.tsx
  src/components/common/buttons/IconButton.tsx
  src/store/toastStore.ts
Labels: Feature, Html&css

#61 [Feat] playlist Item 컴포넌트 작성
  src/components/common/PlaylistItem.tsx
Labels: Feature, Html&css

#62 [Feat] toast 컴포넌트 개선 및 플레이리스트에 사용할 구독(별) 토글버튼 생성 with 토스트
  src/components/common/Toast.tsx
  src/components/playlist/StarToggleButton.tsx
  src/pages/ExamplePage.tsx
  src/store/useToastStore.ts
  src/store/useToggleStore.ts
Labels: Feature, Refactor

#60 [Feat] Input컴포넌트 추가 및 로그인페이지 구현
  public/logo.svg
  src/App.tsx
  src/components/common/Input.tsx
  src/pages/Signin.tsx
  src/utils/ValidateEmail.ts
Labels: Feature, Html&css

#63 [Feat] Likes, Comments 버튼 컴포넌트
  .eslintrc.cjs
  src/components/common/buttons/CommentsButton.tsx
  src/components/common/buttons/LikesButton.tsx
  src/hooks/useLikeCount.ts
  src/layouts/layout/Header.tsx
  src/pages/Search.tsx
  src/store/useLikeStore.ts
  src/utils/formatNumberToK.ts
Labels: Feature

#64 [Feat] flip over와 MyPlaylists 컴포넌트 동시 구현
  src/components/common/buttons/IconTextButton.tsx
  src/components/mypage/FlipCard.tsx
  src/components/mypage/MyPlaylists.tsx
  src/layouts/RootLayout.tsx
  src/pages/ExamplePage.tsx
  src/util/stringUtils.ts
Labels: Feature, Html&css

#68 [feat] bottom sheet 컴포넌트 작성
  src/components/common/PlaylistItem.tsx
  src/components/common/modals/BottomSheet.tsx
  src/pages/Test/ExamplePage.tsx
Labels: Feature, Html&css

#71 [Feat] 토글 트윙클 효과
  src/components/subscriptions/StarAnimation.tsx
  src/components/subscriptions/SubsToggleButton.tsx
  src/pages/ExamplePage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: Feature, Html&css

#74 [Feat] 마이페이지 페이지컴포넌트(#67, #72, #73)
  src/App.tsx
  src/assets/images/default-avatar-man.svg
  src/assets/images/default-avatar-woman.svg
  src/components/mypage/FlipCard.tsx
  src/components/mypage/MyPlaylists.tsx
  src/components/mypage/MyProfile.tsx
  src/constants/path.ts
  src/layouts/layout/Header.tsx
  src/mock/playlists.json
  src/pages/Mypage.tsx
  src/pages/Settings.tsx
  src/styles/theme.ts
  src/types/playlist.d.ts
Labels: Feature, Html&css
